# Generated by Django 4.1 on 2022-09-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
