# Generated by Django 4.1 on 2022-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_alter_photographer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='country',
        ),
        migrations.AddField(
            model_name='photographer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
