# Generated by Django 4.1 on 2022-09-11 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0005_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photographer',
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photographer.photography_package'),
        ),
    ]
